stages:
    - build
variables:
    
before_script: 
    # - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
    stage: build
    script:
        - docker load -i docker_base
        - docker tag docker_base:latest $CI_REGISTRY_IMAGE:latest
        - docker push $CI_REGISTRY_IMAGE:latest
